/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign up (FR-01) */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in (FR-01) */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate refresh token and issue a new access token
         * @description Authenticated via the refresh cookie, not a bearer token. No request body.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out, invalidate refresh token (FR-03) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start Google OAuth (FR-02) */
        get: operations["googleStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth callback (FR-02) */
        get: operations["googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a password reset link (FR-04) */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm password reset with a token (FR-04) */
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update profile (FR-11) */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/users/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload avatar (FR-11) */
        put: operations["uploadAvatar"];
        post?: never;
        /** Remove avatar (FR-11) */
        delete: operations["deleteAvatar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/presence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set presence status (FR-10)
         * @description 'offline' is set automatically on socket disconnect — not settable here.
         */
        patch: operations["setPresence"];
        trace?: never;
    };
    "/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search users by username (FR-05)
         * @description Case-insensitive partial match. Excludes the caller and any users in a block relationship (either direction), server-side.
         */
        get: operations["searchUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user's public profile */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List friends (FR-06) */
        get: operations["listFriends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending requests (FR-06) */
        get: operations["listContactRequests"];
        put?: never;
        /**
         * Send a friend request (FR-06)
         * @description If the target already sent the caller a request, the server auto-accepts and both become friends. Blocked in either direction → 403 BLOCKED.
         */
        post: operations["sendFriendRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/requests/{requestId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a friend request (FR-06) */
        post: operations["acceptFriendRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/requests/{requestId}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline a friend request (FR-06) */
        post: operations["declineFriendRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a contact (FR-07) */
        delete: operations["removeContact"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/blocked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List blocked users (FR-09) */
        get: operations["listBlocked"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Block a user (FR-08)
         * @description Server-enforced (NF-13): blocked pair cannot message, search, or invite each other; existing friendship/requests are removed.
         */
        post: operations["blockUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/blocks/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unblock a user (FR-09) */
        delete: operations["unblockUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List conversations (chat sessions)
         * @description Sorted by lastActivityAt descending. Includes DMs and groups.
         */
        get: operations["listConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/dm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open or create a DM (FR-12)
         * @description Idempotent. 200 if a DM already exists, 201 if newly created. The two users must be contacts; blocked in either direction → 403 BLOCKED.
         */
        post: operations["openDm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single conversation
         * @description Caller must be a participant/member. Non-members get 404 (default) to avoid leaking existence.
         */
        get: operations["getConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a conversation read (FR-14)
         * @description Durable read-marker path. Advances the caller's marker, clears unreadCount, and emits message:status (read) to senders over the socket.
         */
        post: operations["markConversationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversationId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch message history (FR-13)
         * @description Paginates backward in time. data is ordered oldest→newest within the page; nextCursor points to the next older page (null at the start of history). Soft-deleted messages appear with content null and deletedAt set.
         */
        get: operations["listMessages"];
        put?: never;
        /**
         * Send a message (FR-13)
         * @description Persisted before the 201 is returned. Server assigns id/sequence/createdAt and emits message:new to other participants. @mentions create notifications. At least one of content (non-empty) or attachmentIds must be present.
         */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{messageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Soft-delete a message (FR-16)
         * @description Only the sender may delete. Sets deletedAt, nulls content/attachments; the row remains so the placeholder renders. Emits message:deleted.
         */
        delete: operations["deleteMessage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload an attachment (FR-17, P3)
         * @description Two-step: upload returns an id, then reference it in attachmentIds on send. Requires object storage — may be stubbed/disabled until P3.
         */
        post: operations["uploadAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a group (FR-18)
         * @description Creator becomes the first admin. Non-contact/blocked memberIds rejected.
         */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join via invite link (FR-19)
         * @description 200/201 with the group if joined directly; 202 { pending: true } if the join needs admin approval (creates a group_join_request).
         */
        post: operations["joinByLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get group detail */
        get: operations["getGroup"];
        put?: never;
        post?: never;
        /** Delete group (FR-18 lifecycle) — Admin */
        delete: operations["deleteGroup"];
        options?: never;
        head?: never;
        /** Update group profile (FR-23) — Admin */
        patch: operations["updateGroup"];
        trace?: never;
    };
    "/groups/{groupId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members */
        get: operations["listGroupMembers"];
        put?: never;
        /** Add / invite members (FR-19) — Admin or per policy */
        post: operations["addGroupMembers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a member (FR-21) / leave a group (FR-22)
         * @description One endpoint, authorization branches on target. If :userId is another member → caller must be Admin (remove). If :userId is self → any member may leave. Last-admin case → 409 LAST_ADMIN or auto-promote (Phase 4 rule).
         */
        delete: operations["removeGroupMember"];
        options?: never;
        head?: never;
        /**
         * Change member role (FR-20) — Admin
         * @description Server prevents demoting the last admin → 409 LAST_ADMIN.
         */
        patch: operations["changeMemberRole"];
        trace?: never;
    };
    "/groups/{groupId}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload group avatar (FR-23) — Admin */
        put: operations["uploadGroupAvatar"];
        post?: never;
        /** Remove group avatar (FR-23) — Admin */
        delete: operations["deleteGroupAvatar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/invite-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate an invite link (FR-19) — Admin or per policy */
        post: operations["createInviteLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/join-requests/{requestId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a join request (FR-19, conditional) — Admin
         * @description Exists only if the admin-approval join model is adopted (FLAG
         */
        post: operations["acceptJoinRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/join-requests/{requestId}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decline a join request (FR-19, conditional) — Admin
         * @description Exists only if the admin-approval join model is adopted (FLAG
         */
        post: operations["declineJoinRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/invites/{inviteId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a group invitation (FR-19)
         * @description The invited user accepts a direct group invite and becomes a member. The group's conversation is also delivered via conversation:new. Dispatched from a group_invite notification using payload.inviteId + payload.groupId.
         */
        post: operations["acceptGroupInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/invites/{inviteId}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decline a group invitation (FR-19)
         * @description The invited user declines a direct group invite. Dispatched from a group_invite notification using payload.inviteId + payload.groupId.
         */
        post: operations["declineGroupInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List notifications (FR-30)
         * @description Newest first. Message notifications are NOT in this feed (they're unread badges on conversations); this feed is invites, requests, mentions, system.
         */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unread notification count (FR-30) */
        get: operations["getNotificationCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark notifications seen (FR-30)
         * @description Marks all unseen as seen (or specific ids). Seen ≠ resolved — actionable items remain actionable until accepted/declined via their domain endpoints.
         */
        post: operations["markNotificationsSeen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Presence: "online" | "away" | "dnd" | "offline";
        PublicUser: {
            /** Format: uuid */
            id: string;
            username: string;
            displayName: string;
            avatarUrl: string | null;
            bio: string | null;
            presence: components["schemas"]["Presence"];
        };
        SelfUser: components["schemas"]["PublicUser"] & {
            /** Format: email */
            email: string;
            /** Format: date-time */
            createdAt: string;
        };
        ApiError: {
            error: {
                /** @description Stable machine code. Switch on this, not message. */
                code: string;
                message: string;
                details?: unknown;
            };
        };
        /** @enum {string} */
        Relationship: "none" | "request_sent" | "request_received" | "friends" | "blocked" | "blocked_by";
        UserSearchResult: {
            user: components["schemas"]["PublicUser"];
            relationship: components["schemas"]["Relationship"];
        };
        ContactRequest: {
            /** Format: uuid */
            id: string;
            from: components["schemas"]["PublicUser"];
            to: components["schemas"]["PublicUser"];
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {string} */
        ConversationType: "dm" | "group";
        Attachment: {
            /** Format: uuid */
            id: string;
            url: string;
            fileName: string;
            mimeType: string;
            sizeBytes: number;
            /** @enum {string} */
            kind: "image" | "file";
        };
        /**
         * @description 'sending' is a client-only optimistic state, never sent by the server.
         * @enum {string}
         */
        MessageStatus: "sent" | "delivered" | "read";
        Message: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversationId: string;
            /**
             * Format: int64
             * @description Monotonic per conversation; ordering + reconnect-replay cursor.
             */
            sequence: number;
            /** Format: uuid */
            senderId: string;
            /** @description Null when soft-deleted (FR-16). */
            content: string | null;
            attachments: components["schemas"]["Attachment"][];
            status: components["schemas"]["MessageStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            deletedAt: string | null;
            /** @description Echoed back on send to reconcile the optimistic bubble. */
            clientNonce?: string;
        };
        ConversationBase: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["ConversationType"];
            lastMessage: components["schemas"]["Message"] | null;
            /** Format: date-time */
            lastActivityAt: string;
            unreadCount: number;
        };
        DmConversation: components["schemas"]["ConversationBase"] & {
            /** @constant */
            type?: "dm";
            otherUser: components["schemas"]["PublicUser"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "dm";
        };
        /** @enum {string} */
        GroupRole: "admin" | "member";
        GroupConversation: components["schemas"]["ConversationBase"] & {
            /** @constant */
            type?: "group";
            name: string;
            avatarUrl: string | null;
            memberCount: number;
            members: components["schemas"]["PublicUser"][];
            role: components["schemas"]["GroupRole"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "group";
        };
        Conversation: components["schemas"]["DmConversation"] | components["schemas"]["GroupConversation"];
        GroupMember: {
            user: components["schemas"]["PublicUser"];
            role: components["schemas"]["GroupRole"];
            /** Format: date-time */
            joinedAt: string;
        };
        Group: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string | null;
            avatarUrl: string | null;
            /** Format: date-time */
            createdAt: string;
            memberCount: number;
            role: components["schemas"]["GroupRole"];
            /** @description Populated on the detail endpoint only. */
            members?: components["schemas"]["GroupMember"][];
        };
        /** @enum {string} */
        NotificationType: "friend_request" | "friend_request_accepted" | "group_invite" | "group_join_request" | "mention" | "missed_call" | "generic";
        /** @description Ids let the FE dispatch to the correct action endpoint. */
        NotificationPayload: {
            /** Format: uuid */
            requestId?: string;
            /** Format: uuid */
            inviteId?: string;
            /** Format: uuid */
            groupId?: string;
            /** Format: uuid */
            conversationId?: string;
            /** Format: uuid */
            messageId?: string;
            text?: string;
        };
        Notification: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["NotificationType"];
            actor: components["schemas"]["PublicUser"] | null;
            read: boolean;
            /** Format: date-time */
            createdAt: string;
            payload: components["schemas"]["NotificationPayload"];
        };
    };
    responses: {
        /** @description Duplicate or state conflict. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Well-formed but semantically invalid. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Too many requests (NF-11). */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Missing / invalid / expired token. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Uploaded file exceeds the configured limit. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Authenticated but not permitted (includes BLOCKED). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        /** @description Opaque keyset cursor. Omit for the first page. */
        Cursor: string;
        /** @description Page size. Server-capped; default 30. */
        Limit: number;
        GroupId: string;
        UserId: string;
        RequestId: string;
        InviteId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    /** Format: email */
                    email: string;
                    password: string;
                    /** @constant */
                    acceptedTerms: true;
                };
            };
        };
        responses: {
            /** @description Account created; access token returned, refresh cookie set. */
            201: {
                headers: {
                    /** @description refreshToken=…; HttpOnly; Secure; SameSite=Strict */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["SelfUser"];
                        accessToken: string;
                    };
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description username OR email */
                    identifier: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Authenticated; access token returned, refresh cookie set. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["SelfUser"];
                        accessToken: string;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New access token; refresh cookie rotated (old invalidated). */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken: string;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    logout: {
        parameters: {
            query?: {
                /** @description When true, revoke all refresh tokens for the user (optional). */
                all?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out; refresh cookie cleared and token revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    googleStart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to Google's consent screen. */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    googleCallback: {
        parameters: {
            query: {
                code: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description On success: redirect to the frontend with a token handoff and the refresh cookie set. On failure: redirect to {FE_URL}/login?error=oauth_failed. */
            302: {
                headers: {
                    Location?: string;
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Always returned regardless of whether the email exists (no enumeration). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    newPassword: string;
                };
            };
        };
        responses: {
            /** @description Password updated; reset token consumed; sessions revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Reset token invalid (code RESET_TOKEN_INVALID). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SelfUser"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    displayName?: string;
                    bio?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SelfUser"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            422: components["responses"]["ValidationError"];
        };
    };
    uploadAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description New avatar URL. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        avatarUrl: string;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Avatar removed; reverts to initials fallback. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    setPresence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "online" | "away" | "dnd";
                };
            };
        };
        responses: {
            /** @description Updated presence. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        presence: components["schemas"]["Presence"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            422: components["responses"]["ValidationError"];
        };
    };
    searchUsers: {
        parameters: {
            query: {
                q: string;
                /** @description Opaque keyset cursor. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. Server-capped; default 30. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated search results with per-row relationship. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserSearchResult"][];
                        nextCursor: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUser"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    listFriends: {
        parameters: {
            query?: {
                /** @description Opaque keyset cursor. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. Server-capped; default 30. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated friends, each with live-ish presence. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PublicUser"][];
                        nextCursor: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    listContactRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Incoming and outgoing pending requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        incoming: components["schemas"]["ContactRequest"][];
                        outgoing: components["schemas"]["ContactRequest"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    sendFriendRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    userId: string;
                };
            };
        };
        responses: {
            /** @description Pending request created (or friendship if auto-accepted). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactRequest"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    acceptFriendRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Friendship created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        friend: components["schemas"]["PublicUser"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    declineFriendRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request removed; no friendship created. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    removeContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Friendship removed symmetrically. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    listBlocked: {
        parameters: {
            query?: {
                /** @description Opaque keyset cursor. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. Server-capped; default 30. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated blocked users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PublicUser"][];
                        nextCursor: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    blockUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    userId: string;
                };
            };
        };
        responses: {
            /** @description User blocked. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        blockedUser: components["schemas"]["PublicUser"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    unblockUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Block removed (no friendship restored). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    listConversations: {
        parameters: {
            query?: {
                /** @description Opaque keyset cursor. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. Server-capped; default 30. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated conversations, most recent first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Conversation"][];
                        nextCursor: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    openDm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    userId: string;
                };
            };
        };
        responses: {
            /** @description Existing DM conversation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DmConversation"];
                };
            };
            /** @description Newly created DM conversation. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DmConversation"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    markConversationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    lastReadMessageId: string;
                };
            };
        };
        responses: {
            /** @description Read marker advanced. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listMessages: {
        parameters: {
            query?: {
                /** @description Opaque keyset cursor. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. Server-capped; default 30. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated message page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Message"][];
                        nextCursor: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content?: string | null;
                    attachmentIds?: string[];
                    clientNonce?: string;
                };
            };
        };
        responses: {
            /** @description Persisted message (the durable ack). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Message soft-deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Stored attachment metadata. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    description?: string;
                    /** Format: uuid */
                    avatarId?: string;
                    memberIds?: string[];
                };
            };
        };
        responses: {
            /** @description Group created; caller's role is admin. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    joinByLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    inviteToken: string;
                };
            };
        };
        responses: {
            /** @description Joined an existing membership state (idempotent path). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description Joined the group directly. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description Join request created; pending admin approval. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        pending: true;
                    };
                };
            };
            /** @description Invite invalid (code INVITE_INVALID). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group with members populated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group deleted for all members. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    description?: string | null;
                    /** Format: uuid */
                    avatarId?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated group. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    listGroupMembers: {
        parameters: {
            query?: {
                /** @description Opaque keyset cursor. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. Server-capped; default 30. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated members. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GroupMember"][];
                        nextCursor: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    addGroupMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    userIds: string[];
                };
            };
        };
        responses: {
            /** @description Members added and/or invited. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        added: components["schemas"]["GroupMember"][];
                        invited: components["schemas"]["PublicUser"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    removeGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member removed / left. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    changeMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    role: components["schemas"]["GroupRole"];
                };
            };
        };
        responses: {
            /** @description Updated member. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMember"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    uploadGroupAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Avatar uploaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        avatarId: string;
                        avatarUrl: string;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteGroupAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Avatar removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createInviteLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shareable invite link. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        url: string;
                        token: string;
                        /** Format: date-time */
                        expiresAt: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    acceptJoinRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request accepted; member added. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        member: components["schemas"]["GroupMember"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    declineJoinRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request declined. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    acceptGroupInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
                inviteId: components["parameters"]["InviteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitation accepted; caller is now a member. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        group: components["schemas"]["Group"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    declineGroupInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
                inviteId: components["parameters"]["InviteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitation declined. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                /** @description Opaque keyset cursor. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. Server-capped; default 30. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated notifications. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Notification"][];
                        nextCursor: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    getNotificationCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Count of unseen notifications (drives the bell badge). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        count: number;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    markNotificationsSeen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Optional; omit to mark all unseen as seen. */
                    ids?: string[];
                };
            };
        };
        responses: {
            /** @description Notifications marked seen; bell badge cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
}
